# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Ko Minkyu
tagline:          ''
description:      'Android Developer<br>Living in Seoul<br>'
url:              http://kominkyu.github.io
baseurl:          /

author:
  name:           'Minkyu Ko'
  url:            https://facebook.com/risedrag

paginate:         3

# Custom vars
version:          2.1.0

github:
  repo:

gems: [jekyll-paginate, jekyll-gist]
